/* Generated by Yosys 0.62+95 (git sha1 53d8eb43f, clang++ 18.1.8 -fPIC -O3) */

(* src = "rtl/pfe.sv:9.5-25.14" *)
module axis_stream_receive(clk, rst_n, s_axis_tdata, s_axis_tvalid, s_axis_tready, out);
  (* src = "rtl/pfe.sv:10.21-10.24" *)
  input clk;
  wire clk;
  (* src = "rtl/pfe.sv:11.21-11.26" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/pfe.sv:12.27-12.39" *)
  input [7:0] s_axis_tdata;
  wire [7:0] s_axis_tdata;
  (* src = "rtl/pfe.sv:13.21-13.34" *)
  input s_axis_tvalid;
  wire s_axis_tvalid;
  (* src = "rtl/pfe.sv:14.22-14.35" *)
  output s_axis_tready;
  wire s_axis_tready;
  (* src = "rtl/pfe.sv:15.28-15.31" *)
  output [7:0] out;
  reg [7:0] out;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[0] <= 1'h0;
    else if (s_axis_tvalid) out[0] <= s_axis_tdata[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[1] <= 1'h0;
    else if (s_axis_tvalid) out[1] <= s_axis_tdata[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[2] <= 1'h0;
    else if (s_axis_tvalid) out[2] <= s_axis_tdata[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[3] <= 1'h0;
    else if (s_axis_tvalid) out[3] <= s_axis_tdata[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[4] <= 1'h0;
    else if (s_axis_tvalid) out[4] <= s_axis_tdata[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[5] <= 1'h0;
    else if (s_axis_tvalid) out[5] <= s_axis_tdata[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[6] <= 1'h0;
    else if (s_axis_tvalid) out[6] <= s_axis_tdata[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pfe.sv:18.9-23.12" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) out[7] <= 1'h0;
    else if (s_axis_tvalid) out[7] <= s_axis_tdata[7];
  assign s_axis_tready = 1'h1;
endmodule

(* src = "rtl/pfe.sv:29.5-54.14" *)
module dekoder(input_i, o);
  (* src = "rtl/pfe.sv:30.21-30.28" *)
  input [3:0] input_i;
  wire [3:0] input_i;
  (* src = "rtl/pfe.sv:31.28-31.29" *)
  output [6:0] o;
  wire [6:0] o;
  wire [6:0] _00_;
  wire [6:0] _01_;
  wire [6:0] _02_;
  wire [6:0] _03_;
  wire [6:0] _04_;
  wire [6:0] _05_;
  assign _03_[0] = input_i[1] ? 1'h0 : _05_[2];
  assign _03_[1] = input_i[1] ? _05_[2] : input_i[0];
  assign _03_[3] = input_i[1] ? input_i[0] : _05_[2];
  assign _03_[4] = input_i[1] ? input_i[0] : 1'h1;
  assign _03_[5] = input_i[1] ? input_i[0] : 1'h0;
  assign _02_[2] = input_i[1] ? _05_[2] : 1'h0;
  assign _02_[0] = input_i[1] ? 1'h0 : input_i[0];
  assign _02_[5] = input_i[1] ? 1'h1 : input_i[0];
  assign _02_[6] = ~input_i[1];
  assign _01_[0] = input_i[2] ? _02_[0] : _03_[5];
  assign _01_[1] = input_i[2] ? _04_[1] : _03_[5];
  assign _01_[2] = input_i[2] ? _04_[1] : 1'h0;
  assign _01_[3] = input_i[2] ? _03_[5] : _02_[2];
  assign _01_[4] = input_i[2] ? 1'h0 : _02_[0];
  assign _01_[5] = input_i[2] ? _02_[0] : 1'h0;
  assign _01_[6] = input_i[2] ? _03_[0] : 1'h0;
  assign _00_[0] = input_i[2] ? _03_[0] : _02_[0];
  assign _00_[1] = input_i[2] ? _03_[1] : 1'h0;
  assign _00_[2] = input_i[2] ? 1'h0 : _02_[2];
  assign _00_[3] = input_i[2] ? _03_[3] : _02_[0];
  assign _00_[4] = input_i[2] ? _03_[4] : input_i[0];
  assign _00_[5] = input_i[2] ? _03_[5] : _02_[5];
  assign _00_[6] = input_i[2] ? _03_[5] : _02_[6];
  assign o[0] = input_i[3] ? _01_[0] : _00_[0];
  assign o[1] = input_i[3] ? _01_[1] : _00_[1];
  assign o[2] = input_i[3] ? _01_[2] : _00_[2];
  assign o[3] = input_i[3] ? _01_[3] : _00_[3];
  assign o[4] = input_i[3] ? _01_[4] : _00_[4];
  assign o[5] = input_i[3] ? _01_[5] : _00_[5];
  assign o[6] = input_i[3] ? _01_[6] : _00_[6];
  assign _04_[1] = input_i[1] ? 1'h1 : _05_[2];
  assign _05_[2] = ~input_i[0];
  assign { _04_[6:2], _04_[0] } = { _03_[0], _02_[0], 1'h0, _03_[5], _04_[1], _02_[0] };
  assign { _05_[6:3], _05_[1:0] } = { 2'h1, input_i[0], 3'h0 };
  assign { _03_[6], _03_[2] } = { _03_[5], 1'h0 };
  assign { _02_[4:3], _02_[1] } = { input_i[0], _02_[0], 1'h0 };
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/pfe.sv:57.5-105.14" *)
module pfe(clk_i, rst_ni, in_data_i, in_valid_i, in_ready_o, out_data_o, out_valid_o, out_ready_i, sedam_seg_o);
  (* src = "rtl/pfe.sv:60.43-60.48" *)
  input clk_i;
  wire clk_i;
  (* src = "rtl/pfe.sv:61.43-61.49" *)
  input rst_ni;
  wire rst_ni;
  (* src = "rtl/pfe.sv:64.43-64.52" *)
  input [7:0] in_data_i;
  wire [7:0] in_data_i;
  (* src = "rtl/pfe.sv:65.43-65.53" *)
  input in_valid_i;
  wire in_valid_i;
  (* src = "rtl/pfe.sv:66.43-66.53" *)
  output in_ready_o;
  wire in_ready_o;
  (* src = "rtl/pfe.sv:69.45-69.55" *)
  output [7:0] out_data_o;
  wire [7:0] out_data_o;
  (* src = "rtl/pfe.sv:70.44-70.55" *)
  output out_valid_o;
  wire out_valid_o;
  (* src = "rtl/pfe.sv:71.44-71.55" *)
  input out_ready_i;
  wire out_ready_i;
  (* src = "rtl/pfe.sv:72.44-72.55" *)
  output [13:0] sedam_seg_o;
  wire [13:0] sedam_seg_o;
  (* src = "rtl/pfe.sv:78.21-78.34" *)
  wire [7:0] data_register;
  (* src = "rtl/pfe.sv:89.34-89.44" *)
  wire [3:0] donji_nibl;
  (* src = "rtl/pfe.sv:89.21-89.32" *)
  wire [3:0] gornji_nibl;
  (* src = "rtl/pfe.sv:90.21-90.30" *)
  wire [6:0] seg_donji;
  (* src = "rtl/pfe.sv:90.32-90.42" *)
  wire [6:0] seg_gornji;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/pfe.sv:94.17-97.10" *)
  dekoder d1 (
    .input_i(data_register[7:4]),
    .o(seg_gornji)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/pfe.sv:98.17-101.10" *)
  dekoder d2 (
    .input_i(data_register[3:0]),
    .o(seg_donji)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/pfe.sv:79.29-86.10" *)
  axis_stream_receive ulaz (
    .clk(clk_i),
    .out(data_register),
    .rst_n(rst_ni),
    .s_axis_tdata(in_data_i),
    .s_axis_tready(in_ready_o),
    .s_axis_tvalid(in_valid_i)
  );
  assign donji_nibl = data_register[3:0];
  assign gornji_nibl = data_register[7:4];
  assign sedam_seg_o = { seg_gornji, seg_donji };
  assign out_valid_o = in_valid_i;
endmodule
