// jtag_uart_sys.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module jtag_uart_sys (
		input  wire        clk_clk,                      //              clk.clk
		input  wire        jtag_uart_avalon_chipselect,  // jtag_uart_avalon.chipselect
		input  wire        jtag_uart_avalon_address,     //                 .address
		input  wire        jtag_uart_avalon_read_n,      //                 .read_n
		output wire [31:0] jtag_uart_avalon_readdata,    //                 .readdata
		input  wire        jtag_uart_avalon_write_n,     //                 .write_n
		input  wire [31:0] jtag_uart_avalon_writedata,   //                 .writedata
		output wire        jtag_uart_avalon_waitrequest, //                 .waitrequest
		input  wire        reset_reset_n                 //            reset.reset_n
	);

	jtag_uart_sys_jtag_uart_0 jtag_uart_0 (
		.clk            (clk_clk),                      //               clk.clk
		.rst_n          (reset_reset_n),                //             reset.reset_n
		.av_chipselect  (jtag_uart_avalon_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (jtag_uart_avalon_address),     //                  .address
		.av_read_n      (jtag_uart_avalon_read_n),      //                  .read_n
		.av_readdata    (jtag_uart_avalon_readdata),    //                  .readdata
		.av_write_n     (jtag_uart_avalon_write_n),     //                  .write_n
		.av_writedata   (jtag_uart_avalon_writedata),   //                  .writedata
		.av_waitrequest (jtag_uart_avalon_waitrequest), //                  .waitrequest
		.av_irq         ()                              //               irq.irq
	);

endmodule
